on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        test-os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.test-os }}
    steps:
      - uses: actions/checkout@v3
      - name: python installation
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.12"
      - name: dependencies installation
        run: |
          python -m pip install —upgrade pip
      - name: run tests
        run: python ./tests.py